Use HealthcareDB;

/*Checking the two files of carrier claims and the data.*/

SELECT CLM_ID, COUNT(*)
FROM(
	SELECT CLM_ID FROM dbo.carrier1_s1
	UNION ALL
	SELECT CLM_ID FROM dbo.carrier2_s1
) t
GROUP BY CLM_ID
HAVING COUNT(*) > 1; /*Checking if the data is split by same claimIDs or not. Turns out no duplicates here, which means that the data is split vertically (row-wise) because of too much data.*/

/* ---------------------------------Creating Fact Carrier Claims Table. -------------------------------------------------*/
/*Creating the staging table for fact carrier claims.*/

SELECT
    DESYNPUF_ID,
    CLM_ID,
        /*Dates.*/
    TRY_CAST(CLM_FROM_DT AS DATE) AS CLM_FROM_DT,
    TRY_CAST(CLM_THRU_DT AS DATE) AS CLM_THRU_DT,
        /*Claim-level diagnosis codes*/
    ICD9_DGNS_CD_1, ICD9_DGNS_CD_2, ICD9_DGNS_CD_3, ICD9_DGNS_CD_4,
    ICD9_DGNS_CD_5, ICD9_DGNS_CD_6, ICD9_DGNS_CD_7, ICD9_DGNS_CD_8,
        /*Provider NPIs*/
    PRF_PHYSN_NPI_1,  PRF_PHYSN_NPI_2,  PRF_PHYSN_NPI_3,
    PRF_PHYSN_NPI_4,  PRF_PHYSN_NPI_5,  PRF_PHYSN_NPI_6,
    PRF_PHYSN_NPI_7,  PRF_PHYSN_NPI_8,  PRF_PHYSN_NPI_9,
    PRF_PHYSN_NPI_10, PRF_PHYSN_NPI_11, PRF_PHYSN_NPI_12, PRF_PHYSN_NPI_13,
       /*HCPCS codes*/
    HCPCS_CD_1,  HCPCS_CD_2,  HCPCS_CD_3,  HCPCS_CD_4,
    HCPCS_CD_5,  HCPCS_CD_6,  HCPCS_CD_7,  HCPCS_CD_8,
    HCPCS_CD_9,  HCPCS_CD_10, HCPCS_CD_11, HCPCS_CD_12, HCPCS_CD_13,
       /*Amount columns: CAST varchar → DECIMAL. Cleaning for Nulls as well with TRY_CAST.*/
    TRY_CAST(LINE_NCH_PMT_AMT_1  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_1,
    TRY_CAST(LINE_NCH_PMT_AMT_2  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_2,
    TRY_CAST(LINE_NCH_PMT_AMT_3  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_3,
    TRY_CAST(LINE_NCH_PMT_AMT_4  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_4,
    TRY_CAST(LINE_NCH_PMT_AMT_5  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_5,
    TRY_CAST(LINE_NCH_PMT_AMT_6  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_6,
    TRY_CAST(LINE_NCH_PMT_AMT_7  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_7,
    TRY_CAST(LINE_NCH_PMT_AMT_8  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_8,
    TRY_CAST(LINE_NCH_PMT_AMT_9  AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_9,
    TRY_CAST(LINE_NCH_PMT_AMT_10 AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_10,
    TRY_CAST(LINE_NCH_PMT_AMT_11 AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_11,
    TRY_CAST(LINE_NCH_PMT_AMT_12 AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_12,
    TRY_CAST(LINE_NCH_PMT_AMT_13 AS DECIMAL(12,2)) AS LINE_NCH_PMT_AMT_13,

    TRY_CAST(LINE_ALOWD_CHRG_AMT_1  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_1,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_2  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_2,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_3  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_3,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_4  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_4,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_5  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_5,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_6  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_6,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_7  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_7,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_8  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_8,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_9  AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_9,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_10 AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_10,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_11 AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_11,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_12 AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_12,
    TRY_CAST(LINE_ALOWD_CHRG_AMT_13 AS DECIMAL(12,2)) AS LINE_ALOWD_CHRG_AMT_13,

    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_1  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_1,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_2  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_2,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_3  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_3,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_4  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_4,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_5  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_5,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_6  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_6,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_7  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_7,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_8  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_8,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_9  AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_9,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_10 AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_10,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_11 AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_11,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_12 AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_12,
    TRY_CAST(LINE_BENE_PTB_DDCTBL_AMT_13 AS DECIMAL(12,2)) AS LINE_BENE_PTB_DDCTBL_AMT_13,

    TRY_CAST(LINE_COINSRNC_AMT_1  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_1,
    TRY_CAST(LINE_COINSRNC_AMT_2  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_2,
    TRY_CAST(LINE_COINSRNC_AMT_3  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_3,
    TRY_CAST(LINE_COINSRNC_AMT_4  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_4,
    TRY_CAST(LINE_COINSRNC_AMT_5  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_5,
    TRY_CAST(LINE_COINSRNC_AMT_6  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_6,
    TRY_CAST(LINE_COINSRNC_AMT_7  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_7,
    TRY_CAST(LINE_COINSRNC_AMT_8  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_8,
    TRY_CAST(LINE_COINSRNC_AMT_9  AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_9,
    TRY_CAST(LINE_COINSRNC_AMT_10 AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_10,
    TRY_CAST(LINE_COINSRNC_AMT_11 AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_11,
    TRY_CAST(LINE_COINSRNC_AMT_12 AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_12,
    TRY_CAST(LINE_COINSRNC_AMT_13 AS DECIMAL(12,2)) AS LINE_COINSRNC_AMT_13,
        /*Line-level ICD9 codes*/
    LINE_ICD9_DGNS_CD_1,  LINE_ICD9_DGNS_CD_2,  LINE_ICD9_DGNS_CD_3,
    LINE_ICD9_DGNS_CD_4,  LINE_ICD9_DGNS_CD_5,  LINE_ICD9_DGNS_CD_6,
    LINE_ICD9_DGNS_CD_7,  LINE_ICD9_DGNS_CD_8,  LINE_ICD9_DGNS_CD_9,
    LINE_ICD9_DGNS_CD_10, LINE_ICD9_DGNS_CD_11, LINE_ICD9_DGNS_CD_12,
    LINE_ICD9_DGNS_CD_13
INTO stg_carrier_combined
FROM (
    SELECT * FROM dbo.carrier1_s1
    UNION ALL
    SELECT * FROM dbo.carrier2_s1
) t;

/*Creating the fact carrier claims.*/
SELECT DISTINCT
	CLM_ID,
	DESYNPUF_ID,
	CLM_FROM_DT,
	CLM_THRU_DT
INTO fact_carrier_claim
FROM stg_carrier_combined

/*Validating Data.*/
SELECT CLM_ID, COUNT(*)
FROM fact_carrier_claim
GROUP BY CLM_ID
HAVING COUNT(*) > 1;

/*Adding beneficiary_year_key*/
ALTER TABLE fact_carrier_claim
ADD beneficiary_year_key BIGINT NULL;

UPDATE f
SET f.beneficiary_year_key = d.beneficiary_year_key
FROM fact_carrier_claim f
JOIN dim_beneficiary_yearly d
    ON f.DESYNPUF_ID = d.BeneficiaryID
    AND YEAR(f.CLM_FROM_DT) = d.Year;

/*Validating for null beneficiary keys.*/
SELECT COUNT(*) AS unmatched_rows
FROM fact_carrier_claim
WHERE beneficiary_year_key IS NULL;

/* ---------------------------------Creating Bridge Diagnosis Table. -------------------------------------------------*/

CREATE TABLE bridge_carrier_diagnosis (
	ClaimID VARCHAR(50),
	DiagnosisSequence TINYINT,
	ICD9diagnosisCode VARCHAR(10),
	PRIMARY KEY (ClaimID, DiagnosisSequence)
);

INSERT INTO bridge_carrier_diagnosis
SELECT
	CLM_ID,
	DiagnosisSequence,
	ICD9diagnosisCode
FROM stg_carrier_combined
CROSS APPLY (VALUES
	(1, ICD9_DGNS_CD_1),
	(2, ICD9_DGNS_CD_2),
	(3, ICD9_DGNS_CD_3),
	(4, ICD9_DGNS_CD_4),
	(5, ICD9_DGNS_CD_5),
	(6, ICD9_DGNS_CD_6),
	(7, ICD9_DGNS_CD_7),
	(8, ICD9_DGNS_CD_8)
) d(DiagnosisSequence, ICD9diagnosisCode)
WHERE
	ICD9diagnosisCode IS NOT NULL
	AND LTRIM(RTRIM(ICD9diagnosisCode)) <> '' ;

/* ---------------------------------Creating Fact Carrier Claims 'Line' Table. -------------------------------------------------*/

/*Unpivoting the table from multiple columns to rows for easy aggregations at the later stage.*/

INSERT INTO fact_carrier_claim_line
SELECT
    CLM_ID,
    line_num,
    prf_physn_npi,
    hcpcs_cd,
    line_nch_pmt_amt,
    line_alowd_chrg_amt,
    line_bene_ptb_ddctbl_amt,
    line_coinsrnc_amt,
    line_icd9_dgns_cd
FROM stg_carrier_combined
CROSS APPLY (VALUES /*this is where the manual unpivoting has happened.*/
    (1,  PRF_PHYSN_NPI_1,  HCPCS_CD_1,  LINE_NCH_PMT_AMT_1,  LINE_ALOWD_CHRG_AMT_1,  LINE_BENE_PTB_DDCTBL_AMT_1,  LINE_COINSRNC_AMT_1,  LINE_ICD9_DGNS_CD_1),
    (2,  PRF_PHYSN_NPI_2,  HCPCS_CD_2,  LINE_NCH_PMT_AMT_2,  LINE_ALOWD_CHRG_AMT_2,  LINE_BENE_PTB_DDCTBL_AMT_2,  LINE_COINSRNC_AMT_2,  LINE_ICD9_DGNS_CD_2),
    (3,  PRF_PHYSN_NPI_3,  HCPCS_CD_3,  LINE_NCH_PMT_AMT_3,  LINE_ALOWD_CHRG_AMT_3,  LINE_BENE_PTB_DDCTBL_AMT_3,  LINE_COINSRNC_AMT_3,  LINE_ICD9_DGNS_CD_3),
    (4,  PRF_PHYSN_NPI_4,  HCPCS_CD_4,  LINE_NCH_PMT_AMT_4,  LINE_ALOWD_CHRG_AMT_4,  LINE_BENE_PTB_DDCTBL_AMT_4,  LINE_COINSRNC_AMT_4,  LINE_ICD9_DGNS_CD_4),
    (5,  PRF_PHYSN_NPI_5,  HCPCS_CD_5,  LINE_NCH_PMT_AMT_5,  LINE_ALOWD_CHRG_AMT_5,  LINE_BENE_PTB_DDCTBL_AMT_5,  LINE_COINSRNC_AMT_5,  LINE_ICD9_DGNS_CD_5),
    (6,  PRF_PHYSN_NPI_6,  HCPCS_CD_6,  LINE_NCH_PMT_AMT_6,  LINE_ALOWD_CHRG_AMT_6,  LINE_BENE_PTB_DDCTBL_AMT_6,  LINE_COINSRNC_AMT_6,  LINE_ICD9_DGNS_CD_6),
    (7,  PRF_PHYSN_NPI_7,  HCPCS_CD_7,  LINE_NCH_PMT_AMT_7,  LINE_ALOWD_CHRG_AMT_7,  LINE_BENE_PTB_DDCTBL_AMT_7,  LINE_COINSRNC_AMT_7,  LINE_ICD9_DGNS_CD_7),
    (8,  PRF_PHYSN_NPI_8,  HCPCS_CD_8,  LINE_NCH_PMT_AMT_8,  LINE_ALOWD_CHRG_AMT_8,  LINE_BENE_PTB_DDCTBL_AMT_8,  LINE_COINSRNC_AMT_8,  LINE_ICD9_DGNS_CD_8),
    (9,  PRF_PHYSN_NPI_9,  HCPCS_CD_9,  LINE_NCH_PMT_AMT_9,  LINE_ALOWD_CHRG_AMT_9,  LINE_BENE_PTB_DDCTBL_AMT_9,  LINE_COINSRNC_AMT_9,  LINE_ICD9_DGNS_CD_9),
    (10, PRF_PHYSN_NPI_10, HCPCS_CD_10, LINE_NCH_PMT_AMT_10, LINE_ALOWD_CHRG_AMT_10, LINE_BENE_PTB_DDCTBL_AMT_10, LINE_COINSRNC_AMT_10, LINE_ICD9_DGNS_CD_10),
    (11, PRF_PHYSN_NPI_11, HCPCS_CD_11, LINE_NCH_PMT_AMT_11, LINE_ALOWD_CHRG_AMT_11, LINE_BENE_PTB_DDCTBL_AMT_11, LINE_COINSRNC_AMT_11, LINE_ICD9_DGNS_CD_11),
    (12, PRF_PHYSN_NPI_12, HCPCS_CD_12, LINE_NCH_PMT_AMT_12, LINE_ALOWD_CHRG_AMT_12, LINE_BENE_PTB_DDCTBL_AMT_12, LINE_COINSRNC_AMT_12, LINE_ICD9_DGNS_CD_12),
    (13, PRF_PHYSN_NPI_13, HCPCS_CD_13, LINE_NCH_PMT_AMT_13, LINE_ALOWD_CHRG_AMT_13, LINE_BENE_PTB_DDCTBL_AMT_13, LINE_COINSRNC_AMT_13, LINE_ICD9_DGNS_CD_13)
) u(line_num, prf_physn_npi, hcpcs_cd,
    line_nch_pmt_amt, line_alowd_chrg_amt,
    line_bene_ptb_ddctbl_amt, line_coinsrnc_amt,
    line_icd9_dgns_cd) /*This part is creating column names for the unpivoted table.*/
WHERE
     /*NPI must exist and be non-empty.*/
    prf_physn_npi IS NOT NULL
    AND LTRIM(RTRIM(prf_physn_npi)) <> ''
    AND
    /*HCPCS must exist and be non-empty.*/
    hcpcs_cd IS NOT NULL
    AND LTRIM(RTRIM(hcpcs_cd)) <> ''
    AND
    /*At least one amount must be non-zero.*/
    (
        ISNULL(line_nch_pmt_amt, 0)         +
        ISNULL(line_alowd_chrg_amt, 0)      +
        ISNULL(line_coinsrnc_amt, 0)        +
        ISNULL(line_bene_ptb_ddctbl_amt, 0)
    ) > 0;